application: frc-scout
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

inbound_services:
- mail
- xmpp_message

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /ingest/.*
  script: ingest.ingest_main.app

- url: /analysis/.*
  script: analysis.analysis_main.app

- url: /.*
  script: analysis.analysis.app